### ISSUE TITLE
Please define what "degree" does and its appropriate range

### ISSUE THREAD

**Issue by Bobson1729** [Mathias-Fuchs/MinimalSurface#3]
Firstly, thank you for creating this!

Second, in the command line for MinSurfFromCircularBoundary there is a "degree" option. What does this define and what is the appropriate range of values for it.

Thank you!

- Jason

**Comment by Mathias-Fuchs** [comment]
Please take a look at the formula: 
https://github.com/Mathias-Fuchs/MinimalSurface/blob/ad1b9e0fac8393e0a6988157db9e119ab32d2de2/MinSurfaceGH/LaplaceData.cs#L27C37-L27C37
It comes from the analytic solution of a Dirichlet boundary value problem for the Laplace function on the unit disk, and being a holomorphic and antiholomorphic polynomial in the complex variables z and z-bar, it has a degree like any polynomial does. Your question is legitimate but it is not an "issue" of the code. Feel free to read the code and make a pull request to improve it.

**Comment by Bobson1729** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Ok. Thank you. Sorry for the Github etiquette. I am still rather new to Github and didn't realize how to ask a question without filing it as an issue.- Jason                                                                                                                                                                                                                                                                                                                         From: ***@***.***: October 17, 2023 8:26 AMTo: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [Mathias-Fuchs/MinimalSurface] Please define what "degree" does and its appropriate range (Issue #3)  
Closed #3 as completed.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
